"""added time to usersLessonsComplete

Revision ID: 341ad202474d
Revises: 6030c8220550
Create Date: 2021-05-17 20:03:29.018298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341ad202474d'
down_revision = '6030c8220550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersLessonCompleteAssociation', sa.Column('date_completed', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_usersLessonCompleteAssociation_date_completed'), 'usersLessonCompleteAssociation', ['date_completed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usersLessonCompleteAssociation_date_completed'), table_name='usersLessonCompleteAssociation')
    op.drop_column('usersLessonCompleteAssociation', 'date_completed')
    # ### end Alembic commands ###
