"""reinitiated db

Revision ID: 9dad223af21c
Revises: 
Create Date: 2021-05-18 15:39:51.934084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dad223af21c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('adminPrivilege', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_adminPrivilege'), 'user', ['adminPrivilege'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['createdBy'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_name'), 'course', ['name'], unique=False)
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('dateAdded', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['createdBy'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_dateAdded'), 'lesson', ['dateAdded'], unique=False)
    op.create_index(op.f('ix_lesson_name'), 'lesson', ['name'], unique=True)
    op.create_table('courseVideosAssociation',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], )
    )
    op.create_table('usersCoursesAssociation',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('usersLessonCompleteAssociation',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('date_completed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_index(op.f('ix_usersLessonCompleteAssociation_date_completed'), 'usersLessonCompleteAssociation', ['date_completed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usersLessonCompleteAssociation_date_completed'), table_name='usersLessonCompleteAssociation')
    op.drop_table('usersLessonCompleteAssociation')
    op.drop_table('usersCoursesAssociation')
    op.drop_table('courseVideosAssociation')
    op.drop_index(op.f('ix_lesson_name'), table_name='lesson')
    op.drop_index(op.f('ix_lesson_dateAdded'), table_name='lesson')
    op.drop_table('lesson')
    op.drop_index(op.f('ix_course_name'), table_name='course')
    op.drop_table('course')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_adminPrivilege'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
