"""added course complete association table

Revision ID: a09f6404d6ae
Revises: a1300ebd2a1e
Create Date: 2021-05-27 13:51:55.540071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a09f6404d6ae'
down_revision = 'a1300ebd2a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersCourseCompleteDate',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('date_completed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'course_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_usersCourseCompleteDate_date_completed'), 'usersCourseCompleteDate', ['date_completed'], unique=False)
    op.drop_index('ix_usersCourseCompleteAssociation_date_completed', table_name='usersCourseCompleteAssociation')
    op.drop_table('usersCourseCompleteAssociation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersCourseCompleteAssociation',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('course_id', sa.INTEGER(), nullable=True),
    sa.Column('date_completed', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_index('ix_usersCourseCompleteAssociation_date_completed', 'usersCourseCompleteAssociation', ['date_completed'], unique=False)
    op.drop_index(op.f('ix_usersCourseCompleteDate_date_completed'), table_name='usersCourseCompleteDate')
    op.drop_table('usersCourseCompleteDate')
    # ### end Alembic commands ###
