"""added course complete table

Revision ID: a1300ebd2a1e
Revises: aa1e7f9e776b
Create Date: 2021-05-27 09:53:34.276774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1300ebd2a1e'
down_revision = 'aa1e7f9e776b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersCourseCompleteAssociation',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('date_completed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_index(op.f('ix_usersCourseCompleteAssociation_date_completed'), 'usersCourseCompleteAssociation', ['date_completed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usersCourseCompleteAssociation_date_completed'), table_name='usersCourseCompleteAssociation')
    op.drop_table('usersCourseCompleteAssociation')
    # ### end Alembic commands ###
