"""added filenames in lessons and courses

Revision ID: c4224a557878
Revises: 9dad223af21c
Create Date: 2021-05-20 10:21:52.718233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4224a557878'
down_revision = '9dad223af21c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('imgFileLoc', sa.String(length=120), nullable=True))
    op.add_column('lesson', sa.Column('imgFileLoc', sa.String(length=120), nullable=True))
    op.add_column('lesson', sa.Column('vidFileLoc', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'vidFileLoc')
    op.drop_column('lesson', 'imgFileLoc')
    op.drop_column('course', 'imgFileLoc')
    # ### end Alembic commands ###
